### ISSUE TITLE
Broken outlines for » glyph

### ISSUE THREAD

**Issue by fitojb** [mooniak/maname-font#19]
![image](https://github.com/user-attachments/assets/d9b081a5-f1c6-4a0a-b999-f69267f1d0cf)

**Comment by pathumego** [comment]
@fitojb Thanks! will fix this in the next release.

**Comment by pathumego** [comment]
@fitojb This has been fixed in the latest update on Google Fonts.

**Comment by fitojb** [comment]
Thanks a lot for your work, I can confirm!
