### ISSUE TITLE
මනමේ ෆොන්ටයේ කොරල් ‍ඩ්‍රො 2018 (Version 20) හි රෙන්ඩරින් ගැටළුව

### ISSUE THREAD

**Issue by uthmax** [mooniak/maname-font#4]
![corel](https://user-images.githubusercontent.com/38155149/51036207-6f87d880-15d2-11e9-980d-eb216541084b.png)
කොරල් ඩ්‍රෝ 2018 වෙළුම තුළ මනමේ ෆොන්ටයෙන් මේ විදියට තමයි පෙන්වන්නෙ. කොම්බුව අකුර ඇතුළට යනවා. වෙනත් යුනිකෝඩ් අකුරුවල මෙහෙම වෙන්නෙ නැහැ.

**Comment by pathumego** [comment]
තුති ! @uthmax  
This is an issue with the glyph decomposition I think. However the issue is not present on Harfbuzz. And FDK and Fontmake builds result different issues. Have to investigate.

**Comment by pathumego** [comment]
Was an issue with GDEF. Now fixed

**Comment by uthmax** [comment]
Thank you. Please provide a new link.
Ajith
--------------------------------------------------------------------------------------------------------------------

*Silumina Printers (Pvt) Ltd.Making Rubber Stamps with 1 year warranty.*
No.02, 2nd Floor, YMBA Building, Bodhiraja Mawatha, Kurunegala. (Sri Lanka)
Tel: (+94) 0777 299 411
(Formerly known as Youth Max Creations)
