### ISSUE TITLE
fontmake build error

### ISSUE THREAD

**Issue by pathumego** [mooniak/maname-font#9]
'fontmake: Error: In 'instance_ufo/Maname-Regular.ufo': Compiling UFO failed: Illegal line segment point count: 2'

fontmake v3.8.1

**Comment by pathumego** [comment]
GF team is tracking the release here> https://github.com/google/fonts/issues/3842#issuecomment-2027033548

**Comment by pathumego** [comment]
@yanone can you help to get this over the finish line :)

**Comment by yanone** [comment]
Looking into it

**Comment by pathumego** [comment]
Thanks @yanone !
